# Override Klaxit remote Rubocop config
# See https://github.com/klaxit/ruby/blob/master/rubocop.yml
inherit_from:
  - https://git.io/klaxit-rubocop

AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
